Algoritmo "conversaoDeCelsiusParaFahremheit"
// Disciplina   : [Lógica de Programação em JS]
// Professor   : Jailson Obama
// Descrição   : Esse Algoritimo converte de Celcius para Fahrenheit
// Autor(a)    : Fernando Augusto Calixto Alves
// Data atual  : 29/08/2024
Var
graus : real
temperatura : real


Inicio
escreval("quantos graus vc precisa converter EM C? ")
leia(graus)
temperatura <- (9 * graus + 160)/5
escreval("A temperatura em fahrenheit e ", temperatura)


Fimalgoritmo