Algoritmo "Dias Vividos"
// Disciplina   : [Lógica de Programação com js]
// Professor   : Joilson Obama
// Descrição   : Solicita a qtd de anos dias e meses


// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/08/2024
Var
ano, mes, dia : inteiro


Inicio
escreval("qual ano ")
leia(ano)
escreval("quantos meses se passaram do seu aniversario")
leia(mes)
escreval("quantos dias se passaram do seu aniversario")
leia(dias)


Fimalgoritmo