Algoritmo "verificar se e menor de idade (simples)"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Verificar se e maior de idade
// Autor(a)    : Fernando Augusto Calixto Alves
// Data atual  : 05/09/2024
Var
   idade : inteiro


Inicio
   escreval("Escreva a sua idade")
   leia(idade)
   se idade < 18 entao
      escreval("voce e menor de idade")
   senao
         escreval("voce e maior de idade")
   fimse

Fimalgoritmo