Algoritmo "laco enquanto"
// Disciplina   : [Lógica de Programação em JS]
// Professor   : Jailson
// Descrição   : laco de repeticao
// Autor(a)    : Fernando Augusto Calixto Alves
// Data atual  : 09/09/2024
Var
// Seção de Declarações das variáveis 
 contador : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   enquanto contadora <10 faça
   Escreval("Jaja")
   contadora <- contadora +1
   fimenquanto

Fimalgoritmo