Algoritmo "se o numero e menor que 10"
// Disciplina   : [Lógica de Programação]
// Professor   : Joilson Obama
// Descrição   : Algoritmo para ver se o numero e menor que 10
// Autor(a)    : Fernando Augusto Calixto Alves
// Data atual  : 05/09/2024
Var
numero : inteiro


Inicio
escreval("escreval um numero ")
leia(numero)
se numero <10 entao
   escreval("o numero é menor que 10")
senao
   escreval("numero maior que 10")
   fimse
Fimalgoritmo