Algoritmo "antecessor"
// Disciplina   : [Logica de programação de Javascript]
// Professor   : Jaja Silva Obama BA
// Descrição   : esse algoritimo escreve o numero antecessor para o usuario
// Autor(a)    : Fernando Augusto Calixto ALves
// Data atual  : 28/08/2024
Var
antecessor : inteiro
numero : inteiro


Inicio
escreval("Selecione um numero para ser falado o numero antecessor")
leia(numero)
antecessor <- numero -1
escreva("O Numero antecessor seria ", antecessor)


Fimalgoritmo