Algoritmo "areaDoQuadrado"
// Disciplina   : [Lógica de Programação em Javascript]
// Professor   : Joja
// Descrição   : esse algoritimo vai falar a area do quadrado
// Autor(a)    : Fernando Augusto Calixto Alves
// Data atual  : 28/08/2024
Var
altura, largura, area : inteiro


Inicio
escreval("Digite o numero da altura")
leia(altura)
escreval("Digite o numero da largura")
leia(largura)
area <- altura * largura
escreval("A area total do seu quadrado é ", area)


Fimalgoritmo