Algoritmo "areadoretangulo"
// Disciplina   : [Lógica de Programação de Javascript]
// Professor   : Joilson Obama
// Descrição   : Algoritimo vai devolver a area do retangulo
// Autor(a)    : Fernando Augusto Calixto Alves
// Data atual  : 28/08/2024
Var
base, altura , area : inteiro


Inicio
escreval ("Digite a Base do triangulo: ")
leia(base)
escreval("Digite a altura do triangulo: ")
leia(altura)
area <- base * altura
escreva("A area do seu triangulo sera ", area)


Fimalgoritmo