Algoritmo "De Fahrenheits para celcius"
// Disciplina   : [Lógica de Programação]
// Professor   : Jaja
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/09/2024
Var
fahrenheit : inteiro
celcius : real


Inicio
escreval("Quantos fahrenheits esta? ")
leia (fahrenheit)
celcius <- (fahrenheit - 32)* 5/9
escreval ("O valor de celcius e ", celcius)


Fimalgoritmo